# Emogic docker-compose!
# 2025-05-17

services:
  emogic:
    build:
      context: '.'
    container_name: bot_emogic
    user: '${EMOGIC_UID:-1000}:${EMOGIC_GID:-1000}'
    environment:
      - EMOGIC_TOKEN=${EMOGIC_TOKEN}
      - EMOGIC_DUMP_GROUP_IDS=${EMOGIC_DUMP_GROUP_IDS}
      - EMOGIC_DATA_PATH=${EMOGIC_METADATA_PATH:-./metadata}
      - EMOGIC_LOG_LEVEL=${EMOGIC_LOG_LEVEL:-debug}
      - EMOGIC_STICKER_CACHE_SIZE=${EMOGIC_STICKER_CACHE_SIZE:-100}
    volumes:
      - ${EMOGIC_DATA_PATH:-./metadata}:/app/metadata
      - ${EMOGIC_LOGS_PATH:-./logs}:/app/logs
    restart: unless-stopped
